const { Resend } = require('resend');

const resend = new Resend(process.env.RESEND_API_KEY);
const OWNER_EMAIL = process.env.OWNER_EMAIL;
const CONTRACTOR_NAME = process.env.CONTRACTOR_NAME || 'Your Company';

async function sendRenderEmail(contact, projectDetails, originalImageUrl, renderUrl) {
    if (!process.env.RESEND_API_KEY || !OWNER_EMAIL) {
        console.warn('⚠️ Missing RESEND_API_KEY or OWNER_EMAIL. Skipping email notification.');
        return;
    }

    const htmlBody = `
    <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
        <h2 style="color: #2b6cb0;">New Project Render Ready</h2>
        <p>A new automated render has been completed for your client.</p>
        
        <div style="background-color: #f7fafc; padding: 15px; border-radius: 8px; margin: 20px 0;">
            <h3 style="margin-top: 0; color: #4a5568;">Client Details</h3>
            <p><strong>Name:</strong> ${contact.name}</p>
            <p><strong>Phone:</strong> ${contact.phone}</p>
            <a href="https://app.gohighlevel.com/contacts" style="display: inline-block; background: #3182ce; color: white; padding: 8px 15px; text-decoration: none; border-radius: 5px; margin-top: 10px;">View in GoHighLevel</a>
        </div>

        <div style="background-color: #f7fafc; padding: 15px; border-radius: 8px; margin: 20px 0;">
            <h3 style="margin-top: 0; color: #4a5568;">Project Requirements (AI Extracted)</h3>
            <p style="white-space: pre-wrap;">${projectDetails}</p>
        </div>

        <h3 style="color: #4a5568;">Final Render</h3>
        <p>The best render selected by the AI is displayed below:</p>
        <img src="${renderUrl}" alt="Final AI Render" style="max-width: 100%; border-radius: 8px; margin-bottom: 20px;" />

        <p><a href="${renderUrl}" style="color: #3182ce;">Click here to download the full quality render</a></p>
        
        <hr style="border: 1px solid #e2e8f0; margin: 30px 0;" />
        <p style="font-size: 12px; color: #a0aec0;">Generated by ${CONTRACTOR_NAME} AI Agent</p>
    </div>
    `;

    try {
        const { data, error } = await resend.emails.send({
            from: `${CONTRACTOR_NAME} AI <onboarding@resend.dev>`,
            to: [OWNER_EMAIL],
            subject: `New Render Ready — ${contact.name}`,
            html: htmlBody,
        });

        if (error) {
            console.error('Error sending email via Resend:', error);
        } else {
            console.log('✅ Email sent successfully to owner:', data.id);
        }
    } catch (error) {
        console.error('Failed to send email:', error.message);
    }
}

module.exports = { sendRenderEmail };
